import { generateAttributions } from "../licensing/attribution";
import type { OpenBioFigureProject, ProjectObject } from "../project/schema";

export interface PublicationPreflight {
  ready: boolean;
  objectCount: number;
  hiddenObjectCount: number;
  smallTextCount: number;
  titleComplete: boolean;
  provenanceComplete: boolean;
  checks: { level: "pass" | "warning" | "blocker"; message: string }[];
}

function flattenObjects(objects: ProjectObject[]): ProjectObject[] {
  return objects.flatMap((object) =>
    object.kind === "group"
      ? [object, ...flattenObjects(object.children)]
      : [object],
  );
}

export function checkPublicationReadiness(
  project: OpenBioFigureProject,
): PublicationPreflight {
  const objects = flattenObjects(project.objects);
  const visibleObjects = objects.filter((object) => object.visible);
  const hiddenObjectCount = objects.length - visibleObjects.length;
  const smallTextCount = visibleObjects.filter(
    (object) => object.kind === "text" && object.fontSize * object.scaleY < 12,
  ).length;
  const titleComplete =
    project.metadata.title.trim().length > 0 &&
    project.metadata.title.trim().toLocaleLowerCase("en") !== "untitled figure";
  const provenance = generateAttributions(project).check;
  const checks: PublicationPreflight["checks"] = [
    project.objects.length
      ? {
          level: "pass",
          message: `${project.objects.length} top-level object(s) will be exported.`,
        }
      : { level: "blocker", message: "The figure is empty." },
    titleComplete
      ? { level: "pass", message: "The figure has a descriptive title." }
      : {
          level: "warning",
          message: "Rename the figure before publication.",
        },
    provenance.ready
      ? {
          level: "pass",
          message: `${provenance.completeCount} used asset(s) have complete provenance.`,
        }
      : {
          level: "blocker",
          message: `${provenance.incompleteCount} used asset(s) have incomplete provenance.`,
        },
  ];
  if (hiddenObjectCount)
    checks.push({
      level: "warning",
      message: `${hiddenObjectCount} hidden object(s) will not be visible in exports.`,
    });
  if (smallTextCount)
    checks.push({
      level: "warning",
      message: `${smallTextCount} text object(s) are smaller than 12 px after scaling.`,
    });
  if (provenance.modifiedCount)
    checks.push({
      level: "warning",
      message: `${provenance.modifiedCount} asset modification(s) should be disclosed.`,
    });

  return {
    ready:
      project.objects.length > 0 &&
      provenance.ready &&
      !checks.some((check) => check.level === "blocker"),
    objectCount: objects.length,
    hiddenObjectCount,
    smallTextCount,
    titleComplete,
    provenanceComplete: provenance.ready,
    checks,
  };
}

export function buildPublicationReport(project: OpenBioFigureProject): string {
  const preflight = checkPublicationReadiness(project);
  const attribution = generateAttributions(project);
  return [
    `# Publication report for ${project.metadata.title}`,
    "",
    `Generated by OpenBioFigure 0.2.0 from project format ${project.formatVersion}.`,
    "",
    "> This report assists with technical and licensing checks. It is not legal advice and does not replace journal requirements.",
    "",
    "## Figure",
    "",
    `- Canvas: ${project.document.width} × ${project.document.height} px`,
    `- Objects: ${preflight.objectCount}`,
    `- Used scientific assets: ${attribution.check.usedAssetCount}`,
    `- Preflight: ${preflight.ready ? "ready" : "review required"}`,
    "",
    "## Checks",
    "",
    ...preflight.checks.map(
      (check) =>
        `- ${check.level === "pass" ? "PASS" : check.level.toUpperCase()}: ${check.message}`,
    ),
    "",
    "## Required attribution",
    "",
    attribution.check.assets.some((asset) => asset.license.attributionRequired)
      ? attribution.check.assets
          .filter((asset) => asset.license.attributionRequired)
          .map((asset) => `- ${asset.attribution.text}`)
          .join("\n")
      : "No attribution-required bundled assets are used in this figure.",
    "",
  ].join("\n");
}
